### ISSUE TITLE
Infoboard - error

### ISSUE THREAD

**Issue by cejulius** [Ktar5/Info-Board#100]
[19:51:35] [Server thread/INFO]: cejulius issued server command: /infoboard set 2
[19:51:35] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'infoboard' in plugin Info-Board v1.0.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) ~[spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.IncompatibleClassChangeError: Found interface com.sk89q.worldguard.protection.ApplicableRegionSet, but class was expected
	at com.sniperzciinema.infoboard.API.WorldGuard.getRegionsIn(WorldGuard.java:45) ~[?:?]
	at com.sniperzciinema.infoboard.API.WorldGuard.boardsAllowedHere(WorldGuard.java:27) ~[?:?]
	at com.sniperzciinema.infoboard.Scoreboard.Create.createScoreBoard(Create.java:27) ~[?:?]
	at com.sniperzciinema.infoboard.Commands.onCommand(Commands.java:82) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot18.jar:git-Spigot-3ccbe77-a6a57a9]
	... 15 more

**Comment by pixar02** [comment]
Fixed in a newer version!
Close#100
