### ISSUE TITLE
Having Issues getting it working :/

### ISSUE THREAD

**Issue by FuzzyWartface** [Ktar5/Info-Board#108]
So I installed the plugin, just went through the config, and saw that there was already a preset. So I just restarted the server, and I log on and see nothing. I tried /infoboard show/hide and nothing. In console it keeps spamming this:
Task #58 for InfoBoardReborn v1.7.0 generated an exception
 Or this:
Task #57 for InfoBoardReborn v1.7.0 generated an exception
Or this:
Task #56 for InfoBoardReborn v1.7.0 generated an exception

Obviously I'm doing something wrong, as this plugin is just too amazing!

**Comment by pixar02** [comment]
We think you downloaded the wrong version of the plugin (v1.7), we have an update now (v2.0.1)!  If it's still not working let us know

**Comment by FuzzyWartface** [comment]
I downloaded the new version, and deleted the old. However it is not creating the config files from the .jar file.

[20:51:20 ERROR]: Could not load 'plugins/infoboard-2.0.jar' in folder 'plugins'

**Comment by pixar02** [comment]
Make sure all of it's dependcies are installed! Here is a link on how to install: IBR:
Https://github.com/Ktar5/Info-Board/wiki/Installation

**Comment by FuzzyWartface** [comment]
lol. I did'nt see the dependancies before. However it still is'nt loading the infoboard. before infobord, it says it cant load placeholderapi. I think I need to update me server. Currently it is 1.10.2 spigot. So how exactly do I update it? Where do i get the 1.12.2 jar file, and where do I put it?

**Comment by pixar02** [comment]
Could you send us the log of your console? 
You have two choices to get the newest versions for spigot/craftbukkit. 
1) download the BuildTools.jar form spigot and run it with GIT. click on this [link](https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar) to download it now (BuildTools.jar).
2) use this [link](https://getbukkit.org/get/Fpt2yFn7HRTrot5uE1b8NFWtpQlYITgK)

Make sure you update your .bat or .sh file!

**Comment by FuzzyWartface** [comment]
[17:15:22 ERROR]: Could not load 'plugins/PlaceholderAPI-updated.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:154) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:297) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more
[17:15:22 INFO]: Set PluginClassLoader as parallel capable
[17:15:22 ERROR]: Could not load 'plugins/infoboard-2.0.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: PlaceholderAPI
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:297) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]



Where do I put that .jar file btw?

**Comment by pixar02** [comment]
The spigot/craftbukkit jar goes where the old jar is.
By the look of the config you have the wrong PlaceholderAPI version. Use this one: https://www.spigotmc.com/resoucses/placeholderapi.6245

**Comment by FuzzyWartface** [comment]
placeholderapi loaded correctly, however infoboard is having another error message

[17:32:42 ERROR]: Error occurred while enabling InfoBoardReborn v2.0.0 (Is it up to date?)
java.lang.NullPointerException
        at com.infogroup.infoboard.Timers.<init>(Timers.java:20) ~[?:?]
        at com.infogroup.infoboard.InfoBoardReborn.Instance(InfoBoardReborn.java:114) ~[?:?]
        at com.infogroup.infoboard.InfoBoardReborn.onEnable(InfoBoardReborn.java:53) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

**Comment by FuzzyWartface** [comment]
Also I can't update the server I guess. I have a custom world gen and it dosen't work with 1.12.2. I just installed a backup of me server because console kept telling me all my plugins were dying.

**Comment by FuzzyWartface** [comment]
I tried InfoBoard Reborn and all it's dependencies on a new server without any other plugins, but I still get this message:

[11:23:17 ERROR]: Error occurred while enabling InfoBoardReborn v2.0.0 (Is it up to date?)

**Comment by pixar02** [comment]
What server version ar you using? Also did you install a economy plugin (any), since there isn't a spcified one on the wiki

**Comment by pixar02** [comment]
I tested 1.10 with ibr V2.0.0 and it works.
I have: 
* PlaceholderAPI-2.8.2
* Worldguard-6.2.1
* WorldEdit-6.1.7.2
* Vault
* EssentialsX-2.0.1 (economy plugin)
* InfoBoardReborn-2.0.0

**Comment by FuzzyWartface** [comment]
Currently the version is 1.10.2 and I have ViaVersion through to 1.12.2

Hopefully I am able to find the world gen plugin working on 1.12.2
