### ISSUE TITLE
Error TASK.

### ISSUE THREAD

**Issue by TheIntelloBox** [Ktar5/Info-Board#113]
[19:21:51] [Server thread/WARN]: [InfoBoardReborn] Task #197 for InfoBoardReborn v2.0.2 generated an exception
java.lang.NoSuchMethodError: me.armar.plugins.autorank.api.API.getPrimaryGroup(Lorg/bukkit/entity/Player;)Ljava/lang/String;
	at com.extendedclip.papi.expansion.autorank.AutoRankExpansion.onPlaceholderRequest(AutoRankExpansion.java:70) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:342) ~[PlaceholderAPI-2.8.2.jar:?]
	at com.infogroup.infoboard.GetVariables.replaceVariables(GetVariables.java:13) ~[infoboard-2.0.2.jar:?]
	at com.infogroup.infoboard.utils.Messages.getReplacements(Messages.java:56) ~[infoboard-2.0.2.jar:?]
	at com.infogroup.infoboard.utils.Messages.getLine(Messages.java:38) ~[infoboard-2.0.2.jar:?]
	at com.infogroup.infoboard.scoreboard.Create.createScoreBoard(Create.java:131) ~[infoboard-2.0.2.jar:?]
	at com.infogroup.infoboard.scoreboard.Update.updateScoreBoard(Update.java:65) ~[infoboard-2.0.2.jar:?]
	at com.infogroup.infoboard.Timers.lambda$start$1(Timers.java:74) ~[infoboard-2.0.2.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1310]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.2.jar:git-Paper-1310]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1310]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1310]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1310]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1310]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by pixar02** [comment]
This is not our problem. The AutoRank expansion is broken, since it's not ours we can't fix it.
I will notifiy the author of the expansion about this.

**Comment by extendedclip** [comment]
https://api.extendedclip.com/expansions/autorank/versions/autorank-101/

**Comment by TheIntelloBox** [comment]
Okay so how can I fix it ?

**Comment by pixar02** [comment]
Wait for the author to update the expansion.. Also make sure you use the given link above to the most recent version of the expansion.

**Comment by pixar02** [comment]
If you use the updated version of the expansion link above. It should work without an error... if you replace 
%autorank_current_rank% by %autorank_active_path%

**Comment by TheIntelloBox** [comment]
Must I download this expansion ?

**Comment by pixar02** [comment]
If you want to get the rank of the player in AutoRank. Then yes you do. Else you don't
