### ISSUE TITLE
Console- warn

### ISSUE THREAD

**Issue by Gaspa123** [Ktar5/Info-Board#116]
Hi,
I've problem with console.
After i istalled ur plugin, this happend on console
[22:17:02 WARN]: [InfoBoardReborn] Task #24052 for InfoBoardReborn v2.0.2 generated an exception
java.lang.NumberFormatException: For input string: " 3"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_151]
at java.lang.Integer.parseInt(Integer.java:569) ~[?:1.8.0_151]
at java.lang.Integer.valueOf(Integer.java:766) ~[?:1.8.0_151]
at com.infogroup.infoboard.scoreboard.Update.updateScoreBoard(Update.java:116) ~[?:?]
at com.infogroup.infoboard.Timers.lambda$start$1(Timers.java:74) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[mc.jar:git-Spigot-5f38d38-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [mc.jar:git-Spigot-5f38d38-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [mc.jar:git-Spigot-5f38d38-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [mc.jar:git-Spigot-5f38d38-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [mc.jar:git-Spigot-5f38d38-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [mc.jar:git-Spigot-5f38d38-18fbb24]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

And it appears every second. 
Please help me ASAP :) Thanks

**Comment by pixar02** [comment]
Could you send us the Board.yml file and the config.yml file? (with a Pastebin or hastebin link)

**Comment by Gaspa123** [comment]
https://pastebin.com/qutbSAFN

**Comment by pixar02** [comment]
A scoreboard can only have 15 rows. when you use ; you split the 1 row into 2, So if I counted corectely you have 16 rows...

**Comment by Gaspa123** [comment]
Oh I see I'll fix it.
Thank u for help :)

**Comment by Gaspa123** [comment]
Still same problem,but new warn :( I've 10 rows so, I don't know where is the problem

[17:28:43 WARN]: [InfoBoardReborn] Task #3819 for InfoBoardReborn v2.0.2 generated an exception
java.lang.NullPointerException
at com.infogroup.infoboard.utils.Settings.doesWorldHaveScoreBoard(Settings.java:70) ~[?:?]
at com.infogroup.infoboard.scoreboard.Create.createScoreBoard(Create.java:28) ~[?:?]
at com.infogroup.infoboard.scoreboard.Update.updateScoreBoard(Update.java:65) ~[?:?]
at com.infogroup.infoboard.Timers.lambda$start$1(Timers.java:74) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[mc.jar:git-Spigot-5f38d38-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [mc.jar:git-Spigot-5f38d38-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [mc.jar:git-Spigot-5f38d38-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [mc.jar:git-Spigot-5f38d38-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [mc.jar:git-Spigot-5f38d38-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [mc.jar:git-Spigot-5f38d38-18fbb24]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by pixar02** [comment]
Could you send the updated files?

**Comment by Gaspa123** [comment]
Yup, give me 20 min cause I have to go outside

**Comment by Gaspa123** [comment]
I 've fixed it :) thanks

**Comment by lequanglam** [comment]
@Gaspa123 hey, how do you fix it?
