### ISSUE TITLE
Error in Minecraft 1.13.1 using v2.0.4.

### ISSUE THREAD

**Issue by TheIntelloBox** [Ktar5/Info-Board#131]
https://hastebin.com/fazolovasi.css

**Comment by pixar02** [comment]
The error log is empty... could you send it again ? Also is it still happening?

**Comment by TheIntelloBox** [comment]
[15:19:10] [Server thread/INFO]: [InfoBoardReborn] InfoBoardReborn has been disabled (V.2.0.4)
[15:19:10] [Server thread/ERROR]: Error occurred while enabling InfoBoardReborn v2.0.4 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register com.infogroup.infoboard.events.ChangeWorld@1e2f772d while not enabled
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:522) ~[spigot-1.13.1.jar:git-Spigot-2440e18-d0bb0a1]
	at com.infogroup.infoboard.InfoBoardReborn.registerEvents(InfoBoardReborn.java:104) ~[?:?]
	at com.infogroup.infoboard.InfoBoardReborn.onEnable(InfoBoardReborn.java:64) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.1.jar:git-Spigot-2440e18-d0bb0a1]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.1.jar:git-Spigot-2440e18-d0bb0a1]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.1.jar:git-Spigot-2440e18-d0bb0a1]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:427) [spigot-1.13.1.jar:git-Spigot-2440e18-d0bb0a1]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:341) [spigot-1.13.1.jar:git-Spigot-2440e18-d0bb0a1]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:582) [spigot-1.13.1.jar:git-Spigot-2440e18-d0bb0a1]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:545) [spigot-1.13.1.jar:git-Spigot-2440e18-d0bb0a1]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:423) [spigot-1.13.1.jar:git-Spigot-2440e18-d0bb0a1]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:288) [spigot-1.13.1.jar:git-Spigot-2440e18-d0bb0a1]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.1.jar:git-Spigot-2440e18-d0bb0a1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
