### ISSUE TITLE
Java Exception Minecraft 1.8.3

### ISSUE THREAD

**Issue by PereCP** [Ktar5/Info-Board#133]
Hello, when a player joins the server it does not show the scoreboard and continously prints into the console this exception:
[13:22:18] [Server thread/WARN]: [InfoBoardReborn] Task #35 for InfoBoardReborn v2.0.4 generated an exception
java.lang.NullPointerException
	at com.infogroup.infoboard.utils.Settings.doesWorldHaveScoreBoard(Settings.java:71) ~[?:?]
	at com.infogroup.infoboard.scoreboard.Create.createScoreBoard(Create.java:29) ~[?:?]
	at com.infogroup.infoboard.scoreboard.Update.updateScoreBoard(Update.java:71) ~[?:?]
	at com.infogroup.infoboard.Timers.lambda$start$1(Timers.java:83) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:720) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-870264a-0a645a2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]

I do also attach my board.yml file.

InfoBoard:
  '1':
    ShowTime: 20
    global:
      default:
        Title: '&a&lFresh Skyblock'
        Rows:
        - '&b&lRank'
        - '&8Default'
        - '&b&lOnline Players:'
        - '&e%server_online%'
        - '&b&lIsland Level:'
        - '&e%uskyblock_island_level%'
        - '&b&lMoney:'
        - '&e%vault_eco_balance%'
       special:
        Title: '&a&lFresh Skyblock'
        Rows:
        - '&b&lRank'
        - '&eSpecial'
        - '&b&lOnline Players:'
        - '&e%server_online%'
        - '&b&lIsland Level:'
        - '&e%uskyblock_island_level%'
        - '&b&lMoney:'
        - '&e%vault_eco_balance%'
        vip:
        Title: '&a&lFresh Skyblock'
        Rows:
        - '&b&lRank'
        - '&2VIP'
        - '&b&lOnline Players:'
        - '&e%server_online%'
        - '&b&lIsland Level:'
        - '&e%uskyblock_island_level%'
        - '&b&lMoney:'
        - '&e%vault_eco_balance%'
        admin:
        Title: '&a&lFresh Skyblock'
        Rows:
        - '&b&lRank'
        - '&4Admin'
        - '&b&lOnline Players:'
        - '&e%server_online%'
        - '&b&lIsland Level:'
        - '&e%uskyblock_island_level%'
        - '&b&lMoney:'
        - '&e%vault_eco_balance%'
        - '&b&lRAM USADA:'
        - '&e%server_ram_used%/&4%server_ram_total%'
        - '&b&lTPS:'
        - '&e%server_tps%'

And here is my config.yml file:
Updater: true
Debug: false
give-onjoin: true
Static Board: false
Custom Variables:
  <website>: yoursitehere.net
  <plugindev>: Ktar5 & Pixar02
Disabled Worlds:
- DisabledWorld1
- DisabledWorld2
WorldGuard:
  Prevent Showing In:
  - regionNamesAreCapSensitive
  - regionName2
Update Time:
  Lines: 0.5
Scrolling Text:
  Enable: false
  Shift Time: 0.25
Changeable Text:
  Enable: false
  Changeables:
    healthloc:
      option: BLINK
      interval: 1
      text:
      - '&e%player_health_rounded%&a/&c%player_max_health_rounded%'
      - '&a%player_x%&7, &a%player_y%&7, &a%player_z%'
      - '&l%player_first_join_date%'
    titlewelcome:
      option: BLINK
      interval: 1
      text:
      - '&eWelcome &a%player_name%!'
      - '&aWelcome &6%player_name%!'
      - '&6Welcome &e%player_name%!'
Condition:
  Enabled: false
  Conditions:
    health:
      check: '%player_health_rounded%'
      interval: 1
      answers:
        '20': full health
        '10': half health
        '1': close to death
        '0': dead
        default: still alive

Thank you.

**Comment by PCP2001** [comment]
I did also find this error:
[17:26:29] [Server thread/ERROR]: Cannot load plugins\InfoBoardReborn\board.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 56, column 7:
          default:
          ^
expected <block end>, but found BlockMappingStart
 in 'string', line 67, column 8:
           special:
           ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [spigot.jar:git-Spigot-870264a-0a645a2]
	at com.infogroup.infoboard.utils.FileManager.setup(FileManager.java:55) [infoboard-2.0.4.jar:?]
	at com.infogroup.infoboard.InfoBoardReborn.Instance(InfoBoardReborn.java:135) [infoboard-2.0.4.jar:?]
	at com.infogroup.infoboard.InfoBoardReborn.onEnable(InfoBoardReborn.java:59) [infoboard-2.0.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot.jar:git-Spigot-870264a-0a645a2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 56, column 7:
          default:
          ^
expected <block end>, but found BlockMappingStart
 in 'string', line 67, column 8:
           special:
           ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:226) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:400) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	... 17 more

**Comment by pixar02** [comment]
I think when you edited the board.yml file something mis entered. What I mean by that is that maybe 1 line is indented or to far in the line. If you're using Notepad++, or another program, you can see it when it happens.

From the errors you gave in the second message my guess is correct. Check Line 67 in you board.yml file and add or remove a Space. It always helps if you parse any config or file that you just changed. you can do that using [this site](http://yaml-online-parser.appspot.com/) or any other site that you prefer.

**Comment by PCP2001** [comment]
I solved the parsing error by removing two innecessary spaces (and now the YAML Parser recognizes the file), that made dissappear the second error of the logs, but I'm also having the first error:
When a player joins, the console continously spams this error:

[11:05:20] [Server thread/WARN]: [InfoBoardReborn] Task #40 for InfoBoardReborn v2.0.4 generated an exception
java.lang.NullPointerException
	at com.infogroup.infoboard.utils.Settings.doesWorldHaveScoreBoard(Settings.java:71) ~[?:?]
	at com.infogroup.infoboard.scoreboard.Create.createScoreBoard(Create.java:29) ~[?:?]
	at com.infogroup.infoboard.scoreboard.Update.updateScoreBoard(Update.java:71) ~[?:?]
	at com.infogroup.infoboard.Timers.lambda$start$1(Timers.java:83) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:720) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-870264a-0a645a2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]

What can I do?

**Comment by pixar02** [comment]
Could you send your Board.yml through a website... Hastebin or Pastebin are good options for that. It makes it easier to see what could be wrong.

**Comment by PCP2001** [comment]
BOARD.YML: https://pastebin.com/giwkQHT1
CONFIG.YML: https://pastebin.com/kk2HZkSb
ERROR LOG: https://pastebin.com/Fpek35J3

**Comment by pixar02** [comment]
use this as you board.yml file: https://pastebin.com/j5cbbXr5. It should fix it

**Comment by PCP2001** [comment]
Nope, continues spamming the "NullPointerException".
I give you the entire log: https://pastebin.com/K7t9bpge

**Comment by PCP2001** [comment]
What does this mean?

**Comment by pixar02** [comment]
That this get's a priority..

**Comment by PCP2001** [comment]
Ok, thank you.

**Comment by PCP2001** [comment]
Any update?

**Comment by pixar02** [comment]
Yeay the reason this is happening is because you only have 1 board. The plugin tried to get the next board and did all the checks including checking if it's allowed to be in a certain world. but since you don't have a next board it fails to check. Try enabling the Static-board option in the config.
