### ISSUE TITLE
Issues with Check for updates

### ISSUE THREAD

**Issue by land4r** [Ktar5/Info-Board#154]
Whenever I reload the plugin or start the server with check for updates on, this happens:

>infoboardreborn reload
[10:03:06 INFO]: All configs have been reloaded
>infoboardreborn reload
[10:07:13 INFO]: All configs have been reloaded
[10:07:13 INFO]: [InfoBoardReborn] Checking for updates...
[10:07:13 WARN]: [InfoBoardReborn] Could not connect to Spigot!
[10:07:13 WARN]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://www.spigotmc.org/api/general.php
[10:07:13 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[10:07:13 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[10:07:13 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[10:07:13 WARN]:        at com.infogroup.infoboard.utils.UpdateChecker.getVersion(UpdateChecker.java:66)
[10:07:13 WARN]:        at com.infogroup.infoboard.utils.UpdateChecker.checkUpdate(UpdateChecker.java:38)
[10:07:13 WARN]:        at com.infogroup.infoboard.Timers.lambda$start$6(Timers.java:156)
[10:07:13 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[10:07:13 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[10:07:13 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[10:07:13 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[10:07:13 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[10:07:13 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[10:07:13 WARN]:        at java.lang.Thread.run(Unknown Source)
[10:07:13 INFO]: [InfoBoardReborn] online: null
[10:07:13 INFO]: [InfoBoardReborn] plugin: 2.0.5
[10:07:13 WARN]: [InfoBoardReborn] Failed to check for updates, because: java.lang.NullPointerException
[10:07:13 WARN]: java.lang.NullPointerException
[10:07:13 WARN]:        at com.infogroup.infoboard.utils.UpdateChecker.toReadable(UpdateChecker.java:83)
[10:07:13 WARN]:        at com.infogroup.infoboard.utils.UpdateChecker.checkHigher(UpdateChecker.java:28)
[10:07:13 WARN]:        at com.infogroup.infoboard.utils.UpdateChecker.checkUpdate(UpdateChecker.java:43)
[10:07:13 WARN]:        at com.infogroup.infoboard.Timers.lambda$start$6(Timers.java:156)
[10:07:13 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[10:07:13 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[10:07:13 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[10:07:13 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[10:07:13 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[10:07:13 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[10:07:13 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by pixar02** [comment]
I don't know your server setup, if your server does not allow anyother port than the port for minecraft, it won't work. (If you are renting a server this is probably the case)

If not, then you can just ignore it. Spigot only allows to have a check every day, so when you reload you force that check, so Spigot forces back (so to speak). 

If you do not like this error and don't want to see it again you can turn of the updater in the config, but you will have to check the recource page yourself for updates.
