### ISSUE TITLE
Error updates

### ISSUE THREAD

**Issue by TheKlimoT** [Ktar5/Info-Board#155]
[19:34:22 WARN]: [InfoBoardReborn] Failed to check for updates, because: java.lang.NullPointerException
[19:34:22 WARN]: java.lang.NullPointerException
[19:34:22 WARN]:        at com.infogroup.infoboard.utils.UpdateChecker.toReadable(UpdateChecker.java:83)
[19:34:22 WARN]:        at com.infogroup.infoboard.utils.UpdateChecker.checkHigher(UpdateChecker.java:28)
[19:34:22 WARN]:        at com.infogroup.infoboard.utils.UpdateChecker.checkUpdate(UpdateChecker.java:43)
[19:34:22 WARN]:        at com.infogroup.infoboard.Timers.lambda$start$6(Timers.java:156)
[19:34:22 WARN]:        at com.infogroup.infoboard.Timers$$Lambda$418/1707408662.run(Unknown Source)
[19:34:22 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[19:34:22 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[19:34:22 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
[19:34:22 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[19:34:22 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[19:34:22 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[19:34:22 WARN]:        at java.lang.Thread.run(Thread.java:745)

**Comment by pixar02** [comment]
You can disable it in the config.

> Updater: false

**Comment by ruudschmitz** [comment]
Is this the solution for my case too ? And is this a solution or just a work-around until a definite solution becomes available. Because what use is an auto-update function if it does not work ?

**Comment by pixar02** [comment]
At the moment it is just a "solution" for the error.
