### ISSUE TITLE
please help us with this error 

### ISSUE THREAD

**Issue by ruudschmitz** [Ktar5/Info-Board#158]
[09:57:48 WARN]: [InfoBoardReborn] Failed to check for updates, because: java.lang.NullPointerException
[09:57:48 WARN]: java.lang.NullPointerException
[09:57:48 WARN]: at com.infogroup.infoboard.utils.UpdateChecker.toReadable(UpdateChecker.java:83)
[09:57:48 WARN]: at com.infogroup.infoboard.utils.UpdateChecker.checkHigher(UpdateChecker.java:28)
[09:57:48 WARN]: at com.infogroup.infoboard.utils.UpdateChecker.checkUpdate(UpdateChecker.java:43)
[09:57:48 WARN]: at com.infogroup.infoboard.Timers.lambda$start$6(Timers.java:156)
[09:57:48 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[09:57:48 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[09:57:48 WARN]: at com.infogroup.infoboard.utils.UpdateChecker.toReadable(UpdateChecker.java:83)(B
[09:57:48 WARN]: at com.infogroup.infoboard.utils.UpdateChecker.checkHigher(UpdateChecker.java:28)(B
[09:57:48 WARN]: at com.infogroup.infoboard.utils.UpdateChecker.checkUpdate(UpdateChecker.java:43)(B
[09:57:48 WARN]: at com.infogroup.infoboard.Timers.lambda$start$6(Timers.java:156)(B
[09:57:48 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)(B
[09:57:48 WARN]: at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)(B
[09:57:48 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1292)(B
[09:57:48 WARN]: at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377)(B
[09:57:48 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213)(B
[09:57:48 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001)(B
[09:57:48 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)(B
[09:57:48 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)(B

**Comment by SmoTHyG** [comment]
Is just a warn because the version of the plugin is outdated. Try the plugin in version 1.15 or before 1.15
