### ISSUE TITLE
InfoBoardReborn v2.0.5 generated an exception, help plz

### ISSUE THREAD

**Issue by PandarenzOwO** [Ktar5/Info-Board#162]
IBR it's causing an exception idk why, the error code it's here:

`[06:20:49 WARN]: [InfoBoardReborn] Task #21853 for InfoBoardReborn v2.0.5 generated an exception
java.lang.ArrayIndexOutOfBoundsException: null
        at java.util.HashMap.keysToArray(HashMap.java:952) ~[?:?]
        at java.util.HashMap$KeySet.toArray(HashMap.java:995) ~[?:?]
        at java.util.ArrayList.<init>(ArrayList.java:181) ~[?:?]
        at com.google.common.collect.Lists.newArrayList(Lists.java:149) ~[patched_1.17.jar:git-Paper-79]
        at net.minecraft.world.scores.Scoreboard.getTrackedPlayers(Scoreboard.java:115) ~[patched_1.17.jar:git-Paper-79]
        at org.bukkit.craftbukkit.v1_17_R1.scoreboard.CraftScoreboard.getEntries(CraftScoreboard.java:221) ~[patched_1.17.jar:git-Paper-79]
        at org.bukkit.craftbukkit.v1_17_R1.scoreboard.CraftScoreboard.getEntries(CraftScoreboard.java:19) ~[patched_1.17.jar:git-Paper-79]
        at com.infogroup.infoboard.scoreboard.Board.update(Board.java:182) ~[?:?]
        at com.infogroup.infoboard.scoreboard.Update.updateScoreBoard(Update.java:127) ~[?:?]
        at com.infogroup.infoboard.Timers.lambda$start$1(Timers.java:83) ~[?:?]
        at com.infogroup.infoboard.Timers$$Lambda$5990/0x00000000d695e908.run(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-79]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-79]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-79]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-79]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-79]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-79]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-79]
        at net.minecraft.server.MinecraftServer$$Lambda$3630/0x0000000061f31f00.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Thread.java:883) [?:?]
`

My server is running on 1.17 with paper bukkit
I hope u can help me, ty

**Comment by pixar02** [comment]
The plugin has not been tested for any version higher then 1.15 (Still working on the recode, which will support higher version)
