### ISSUE TITLE
IBR warn spam

### ISSUE THREAD

**Issue by SmoTHyG** [Ktar5/Info-Board#163]
I need help. I don't know why the plugin keeps spamming me this in the console and only when I'm online. I'm using ph, ess, vault, wg, we plugins.

[23:17:53] [Server thread/WARN]: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
[23:17:53] [Server thread/WARN]: 	at Vault.jar//net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPlayerGroups(Permission_SuperPerms.java:91)
[23:17:53] [Server thread/WARN]: 	at Vault.jar//net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.java:637)
[23:17:53] [Server thread/WARN]: 	at InfoBoard-2.0.6.jar//com.infogroup.infoboard.api.Vault.getRank(Vault.java:24)
[23:17:53] [Server thread/WARN]: 	at InfoBoard-2.0.6.jar//com.infogroup.infoboard.scoreboard.Update.updateScoreBoard(Update.java:84)
[23:17:53] [Server thread/WARN]: 	at InfoBoard-2.0.6.jar//com.infogroup.infoboard.Timers.lambda$start$1(Timers.java:83)
[23:17:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[23:17:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[23:17:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559)
[23:17:53] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
[23:17:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475)
[23:17:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274)
[23:17:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[23:17:53] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by SmoTHyG** [comment]
SOLVED! I needed a permission plugin (luckperms)
