### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pl4ntnet** [Ktar5/Info-Board#24]
The Plugin does not work, this is the error text:

Task #1046 for InfoBoardReborn v1.0.0 generated an exception
java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected
	at com.ktar5.infoboard.API.WorldGuard.getRegionsIn(WorldGuard.java:45) ~[?:?]
	at com.ktar5.infoboard.API.WorldGuard.boardsAllowedHere(WorldGuard.java:27) ~[?:?]
	at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:43) ~[?:?]
	at com.ktar5.infoboard.Timers$2.run(Timers.java:94) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-1d14d5f-ba32592]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-1d14d5f-ba32592]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [craftbukkit.jar:git-Spigot-1d14d5f-ba32592]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [craftbukkit.jar:git-Spigot-1d14d5f-ba32592]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [craftbukkit.jar:git-Spigot-1d14d5f-ba32592]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit.jar:git-Spigot-1d14d5f-ba32592]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]

**Comment by duuhnuts** [comment]
Update WorldGuard.

**Comment by duuhnuts** [comment]
Or if it is already updated, renew the server jar
