### ISSUE TITLE
Spamming me!

### ISSUE THREAD

**Issue by Andreaskal** [Ktar5/Info-Board#30]
Hi, i have installed this plugin and when im on the server it doesn't show anything and if i use /ib show it just say "Not Hidden" and in the console it just say:

[17:33:14 WARN]: [InfoBoardReborn] Task #48 for InfoBoardReborn v1.7.0 generated
 an exception
java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/en
tity/Player;
        at com.ktar5.infoboard.Timers$2.run(Timers.java:109) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java
:53) ~[craftbukkit.jar:git-Bukkit-d432434]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHea
rtbeat(CraftScheduler.java:349) [craftbukkit.jar:git-Bukkit-d432434]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:6
83) [craftbukkit.jar:git-Bukkit-d432434]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
35) [craftbukkit.jar:git-Bukkit-d432434]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
32) [craftbukkit.jar:git-Bukkit-d432434]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:540) [craftbukkit.jar:git-Bukkit-d432434]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]

every second!!!
please help!

**Comment by Fortifier42** [comment]
It isn't updated to 1.8.7 yet. Give it time.

**Comment by Andreaskal** [comment]
damn!
thx
