### ISSUE TITLE
Not working( Pls help!

### ISSUE THREAD

**Issue by Argalarg** [Ktar5/Info-Board#39]
Minecraft 1.8.x
If i starting server...
![hlpmepls](https://cloud.githubusercontent.com/assets/13391340/8760929/55289e64-2d48-11e5-8c49-3621f326e1fd.png)
[11:28:54 INFO]: [InfoBoardReborn] Enabling InfoBoardReborn v1.7.0
[11:28:55 ERROR]: Error occurred while enabling InfoBoardReborn v1.7.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/milkbowl/vault/economy/Economy
        at com.ktar5.infoboard.API.Vault.setupEconomy(Vault.java:70) ~[?:?]
        at com.ktar5.infoboard.API.Vault.load(Vault.java:51) ~[?:?]
        at com.ktar5.infoboard.InfoBoard.onEnable(InfoBoard.java:115) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbkkt.jar:git-Bukkit-7d0f836]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [craftbkkt.jar:git-Bukkit-7d0f836]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbkkt.jar:git-Bukkit-7d0f836]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:341) [craftbkkt.jar:git-Bukkit-7d0f836]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:313) [craftbkkt.jar:git-Bukkit-7d0f836]
        at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:408) [craftbkkt.jar:git-Bukkit-7d0f836]
        at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:374) [craftbkkt.jar:git-Bukkit-7d0f836]
        at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:329) [craftbkkt.jar:git-Bukkit-7d0f836]
        at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:236) [craftbkkt.jar:git-Bukkit-7d0f836]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:501) [craftbkkt.jar:git-Bukkit-7d0f836]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_76]
Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.economy.Economy
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_76]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_76]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_76]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_76]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbkkt.jar:git-Bukkit-7d0f836]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbkkt.jar:git-Bukkit-7d0f836]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_76]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_76]
        ... 14 more
and when i join server infoboard is not working...
Please help!!!
P.S. Sorry, bad English

**Comment by sam4215** [comment]
@Argalarg you need Vault.

**Comment by duuhnuts** [comment]
You need Vault. http://dev.bukkit.org/bukkit-plugins/vault/files
