### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by yuuuup** [Ktar5/Info-Board#7]
The latest version of InfoBoardReborn will not run on my 1.8.3, which it should because all the other 1.8x so far are all compatible with each other. In my server log after running my server with IBR it says:  

[07:38:54] [Server thread/ERROR]: Error occurred while enabling InfoBoardReborn v1.7.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/milkbowl/vault/economy/Economy
	at com.ktar5.infoboard.API.Vault.setupEconomy(Vault.java:70) ~[?:?]
	at com.ktar5.infoboard.API.Vault.load(Vault.java:51) ~[?:?]
	at com.ktar5.infoboard.InfoBoard.onEnable(InfoBoard.java:115) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.3.jar:git-Spigot-ea179b3-6e0120a]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8.3.jar:git-Spigot-ea179b3-6e0120a]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.3.jar:git-Spigot-ea179b3-6e0120a]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.3.jar:git-Spigot-ea179b3-6e0120a]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.3.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [spigot-1.8.3.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [spigot-1.8.3.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.8.3.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [spigot-1.8.3.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot-1.8.3.jar:git-Spigot-ea179b3-6e0120a]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.economy.Economy
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_40]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.3.jar:git-Spigot-ea179b3-6e0120a]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.3.jar:git-Spigot-ea179b3-6e0120a]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]

Please help! I rely on this amazing plugin for my server.

Thanks,

yuuuup

**Comment by yuuuup** [comment]
Sorry, never mind

**Comment by yuuuup** [comment]
Sorry, never mind
