### ISSUE TITLE
Error Spamming my consol. Can anyone help?

### ISSUE THREAD

**Issue by ItzDeBeast** [Ktar5/Info-Board#78]
Hey, This keeps spamming my consol. Can someone help?

[18:54:55] [Server thread/WARN]: [InfoBoardReborn] Task #230 for InfoBoardReborn v1.7.0 generated an exception java.lang.NoSuchMethodError: ru.tehkode.permissions.PermissionManager.getUser(Ljava/util/UUID;)Lru/tehkode/permissions/PermissionUser; at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getUser(Permission_PermissionsEx.java:243) ~[?:?] at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getPlayerGroups(Permission_PermissionsEx.java:252) ~[?:?] at com.ktar5.infoboard.API.Vault.getRank(Vault.java:24) ~[?:?] at com.ktar5.infoboard.Scoreboard.Create.createScoreBoard(Create.java:43) ~[?:?] at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:56) ~[?:?] at com.ktar5.infoboard.Timers$2.run(Timers.java:111) ~[?:?] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-07c3001] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-07c3001] at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-07c3001] at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-07c3001] at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-07c3001] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-07c3001] at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]

**Comment by ItzDeBeast** [comment]
now its Task #64 for InfoBoardReborn v1.7.0 generated an exception :(
