### ISSUE TITLE
help 1.8 version 

### ISSUE THREAD

**Issue by reede2** [Ktar5/Info-Board#90]
[09:12:14] [Server thread/WARN]: [InfoBoardReborn] Task #80 for InfoBoardReborn v1.7.0 generated an exception
java.lang.IllegalArgumentException: Illegal group reference
    at java.util.regex.Matcher.appendReplacement(Matcher.java:857) ~[?:1.8.0_45]
    at java.util.regex.Matcher.replaceAll(Matcher.java:955) ~[?:1.8.0_45]
    at java.lang.String.replaceAll(String.java:2211) ~[?:1.8.0_45]
    at com.ktar5.infoboard.Variables.ServerVariables.replaceVariables(ServerVariables.java:26) ~[?:?]
    at com.ktar5.infoboard.GetVariables.replaceVariables(GetVariables.java:52) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getReplacements(Messages.java:50) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getLine(Messages.java:35) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getTitle(Messages.java:80) ~[?:?]
    at com.ktar5.infoboard.Scoreboard.Create.createScoreBoard(Create.java:69) ~[?:?]
    at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:56) ~[?:?]
    at com.ktar5.infoboard.Timers$2.run(Timers.java:111) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) ~[minecraft_server.jar:git-Bukkit-d27e6d0]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:679) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[09:12:16] [Server thread/WARN]: [InfoBoardReborn] Task #80 for InfoBoardReborn v1.7.0 generated an exception
java.lang.IllegalArgumentException: Illegal group reference
    at java.util.regex.Matcher.appendReplacement(Matcher.java:857) ~[?:1.8.0_45]
    at java.util.regex.Matcher.replaceAll(Matcher.java:955) ~[?:1.8.0_45]
    at java.lang.String.replaceAll(String.java:2211) ~[?:1.8.0_45]
    at com.ktar5.infoboard.Variables.ServerVariables.replaceVariables(ServerVariables.java:26) ~[?:?]
    at com.ktar5.infoboard.GetVariables.replaceVariables(GetVariables.java:52) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getReplacements(Messages.java:50) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getLine(Messages.java:35) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getTitle(Messages.java:80) ~[?:?]
    at com.ktar5.infoboard.Scoreboard.Create.createScoreBoard(Create.java:69) ~[?:?]
    at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:56) ~[?:?]
    at com.ktar5.infoboard.Timers$2.run(Timers.java:111) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) ~[minecraft_server.jar:git-Bukkit-d27e6d0]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:679) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[09:12:18] [Server thread/WARN]: [InfoBoardReborn] Task #80 for InfoBoardReborn v1.7.0 generated an exception
java.lang.IllegalArgumentException: Illegal group reference
    at java.util.regex.Matcher.appendReplacement(Matcher.java:857) ~[?:1.8.0_45]
    at java.util.regex.Matcher.replaceAll(Matcher.java:955) ~[?:1.8.0_45]
    at java.lang.String.replaceAll(String.java:2211) ~[?:1.8.0_45]
    at com.ktar5.infoboard.Variables.ServerVariables.replaceVariables(ServerVariables.java:26) ~[?:?]
    at com.ktar5.infoboard.GetVariables.replaceVariables(GetVariables.java:52) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getReplacements(Messages.java:50) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getLine(Messages.java:35) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getTitle(Messages.java:80) ~[?:?]
    at com.ktar5.infoboard.Scoreboard.Create.createScoreBoard(Create.java:69) ~[?:?]
    at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:56) ~[?:?]
    at com.ktar5.infoboard.Timers$2.run(Timers.java:111) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) ~[minecraft_server.jar:git-Bukkit-d27e6d0]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:679) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[09:12:19] [Server thread/INFO]: reede2 issued server command: /info
[09:12:20] [Server thread/WARN]: [InfoBoardReborn] Task #80 for InfoBoardReborn v1.7.0 generated an exception
java.lang.IllegalArgumentException: Illegal group reference
    at java.util.regex.Matcher.appendReplacement(Matcher.java:857) ~[?:1.8.0_45]
    at java.util.regex.Matcher.replaceAll(Matcher.java:955) ~[?:1.8.0_45]
    at java.lang.String.replaceAll(String.java:2211) ~[?:1.8.0_45]
    at com.ktar5.infoboard.Variables.ServerVariables.replaceVariables(ServerVariables.java:26) ~[?:?]
    at com.ktar5.infoboard.GetVariables.replaceVariables(GetVariables.java:52) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getReplacements(Messages.java:50) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getLine(Messages.java:35) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getTitle(Messages.java:80) ~[?:?]
    at com.ktar5.infoboard.Scoreboard.Create.createScoreBoard(Create.java:69) ~[?:?]
    at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:56) ~[?:?]
    at com.ktar5.infoboard.Timers$2.run(Timers.java:111) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) ~[minecraft_server.jar:git-Bukkit-d27e6d0]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:679) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[09:12:27] [Server thread/INFO]: reede2 issued server command: /chestcommands open hub
[09:12:28] [Server thread/INFO]: reede2 issued server command: /warp TNTRUN
[09:12:31] [Server thread/WARN]: [InfoBoardReborn] Task #79 for InfoBoardReborn v1.7.0 generated an exception
java.lang.IllegalArgumentException: Illegal group reference
    at java.util.regex.Matcher.appendReplacement(Matcher.java:857) ~[?:1.8.0_45]
    at java.util.regex.Matcher.replaceAll(Matcher.java:955) ~[?:1.8.0_45]
    at java.lang.String.replaceAll(String.java:2211) ~[?:1.8.0_45]
    at com.ktar5.infoboard.Variables.ServerVariables.replaceVariables(ServerVariables.java:26) ~[?:?]
    at com.ktar5.infoboard.GetVariables.replaceVariables(GetVariables.java:52) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getReplacements(Messages.java:50) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getLine(Messages.java:35) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getTitle(Messages.java:80) ~[?:?]
    at com.ktar5.infoboard.Scoreboard.Create.createScoreBoard(Create.java:69) ~[?:?]
    at com.ktar5.infoboard.Timers$1.run(Timers.java:90) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) ~[minecraft_server.jar:git-Bukkit-d27e6d0]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:679) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[09:12:32] [Server thread/WARN]: [InfoBoardReborn] Task #80 for InfoBoardReborn v1.7.0 generated an exception
java.lang.IllegalArgumentException: Illegal group reference
    at java.util.regex.Matcher.appendReplacement(Matcher.java:857) ~[?:1.8.0_45]
    at java.util.regex.Matcher.replaceAll(Matcher.java:955) ~[?:1.8.0_45]
    at java.lang.String.replaceAll(String.java:2211) ~[?:1.8.0_45]
    at com.ktar5.infoboard.Variables.ServerVariables.replaceVariables(ServerVariables.java:26) ~[?:?]
    at com.ktar5.infoboard.GetVariables.replaceVariables(GetVariables.java:52) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getReplacements(Messages.java:50) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getLine(Messages.java:35) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getTitle(Messages.java:80) ~[?:?]
    at com.ktar5.infoboard.Scoreboard.Create.createScoreBoard(Create.java:69) ~[?:?]
    at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:56) ~[?:?]
    at com.ktar5.infoboard.Timers$2.run(Timers.java:111) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) ~[minecraft_server.jar:git-Bukkit-d27e6d0]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:679) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[09:12:34] [Server thread/WARN]: [InfoBoardReborn] Task #80 for InfoBoardReborn v1.7.0 generated an exception
java.lang.IllegalArgumentException: Illegal group reference
    at java.util.regex.Matcher.appendReplacement(Matcher.java:857) ~[?:1.8.0_45]
    at java.util.regex.Matcher.replaceAll(Matcher.java:955) ~[?:1.8.0_45]
    at java.lang.String.replaceAll(String.java:2211) ~[?:1.8.0_45]
    at com.ktar5.infoboard.Variables.ServerVariables.replaceVariables(ServerVariables.java:26) ~[?:?]
    at com.ktar5.infoboard.GetVariables.replaceVariables(GetVariables.java:52) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getReplacements(Messages.java:50) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getLine(Messages.java:35) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getTitle(Messages.java:80) ~[?:?]
    at com.ktar5.infoboard.Scoreboard.Create.createScoreBoard(Create.java:69) ~[?:?]
    at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:56) ~[?:?]
    at com.ktar5.infoboard.Timers$2.run(Timers.java:111) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) ~[minecraft_server.jar:git-Bukkit-d27e6d0]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:679) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[09:12:36] [Server thread/WARN]: [InfoBoardReborn] Task #80 for InfoBoardReborn v1.7.0 generated an exception
java.lang.IllegalArgumentException: Illegal group reference
    at java.util.regex.Matcher.appendReplacement(Matcher.java:857) ~[?:1.8.0_45]
    at java.util.regex.Matcher.replaceAll(Matcher.java:955) ~[?:1.8.0_45]
    at java.lang.String.replaceAll(String.java:2211) ~[?:1.8.0_45]
    at com.ktar5.infoboard.Variables.ServerVariables.replaceVariables(ServerVariables.java:26) ~[?:?]
    at com.ktar5.infoboard.GetVariables.replaceVariables(GetVariables.java:52) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getReplacements(Messages.java:50) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getLine(Messages.java:35) ~[?:?]
    at com.ktar5.infoboard.Util.Messages.getTitle(Messages.java:80) ~[?:?]
    at com.ktar5.infoboard.Scoreboard.Create.createScoreBoard(Create.java:69) ~[?:?]
    at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:56) ~[?:?]
    at com.ktar5.infoboard.Timers$2.run(Timers.java:111) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) ~[minecraft_server.jar:git-Bukkit-d27e6d0]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:679) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:628) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:536) [minecraft_server.jar:git-Bukkit-d27e6d0]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

**Comment by Mine2bKing** [comment]
I have this to!

**Comment by PabloGamer380YT** [comment]
Yo tambien presento este problema 
No encontraron alguna posible solucion??

**Comment by ThemInspectors** [comment]
Wait for an update Everything est broken

**Comment by pixar02** [comment]
It is fixed !
https://dev.bukkit.org/projects/ib-reborn
