### ISSUE TITLE
Help 1.7.10 Cauldron Bukkit

### ISSUE THREAD

**Issue by DevinderFTW** [Ktar5/Info-Board#91]
[18:36:29 WARN]: [InfoBoardReborn] Task #175 for InfoBoardReborn v1.0.0 generated an exception
java.lang.IllegalArgumentException: Display name 'ºlWelcome To PixelMania - Pokemon' is longer than the limit of 32 characters
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[Validate.class:2.6]
        at org.bukkit.craftbukkit.v1_7_R4.scoreboard.CraftObjective.setDisplayName(CraftObjective.java:40) ~[CraftObjective.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at com.ktar5.infoboard.Scoreboard.Board.setTitle(Board.java:164) ~[?:?]
        at com.ktar5.infoboard.Scoreboard.Create.createScoreBoard(Create.java:61) ~[?:?]
        at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:47) ~[?:?]
        at com.ktar5.infoboard.Timers$2.run(Timers.java:94) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:862) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]

having this problem on my console...

**Comment by pixar02** [comment]
A single row can only be 32 Characters! If you want more you could Scroll the text
