### ISSUE TITLE
Task #532 Issue! Help Please! Respond Quick!

### ISSUE THREAD

**Issue by Jackypants101** [Ktar5/Info-Board#97]
For some reason every single scoreboard plugin doesn't work on my server it generates something on the line with not being able to get pex group. the task #532 didn't work. Please help. Respond Soon!!

The Error:
[17:04:25 WARN]: [InfoBoardReborn] Task #532 for InfoBoardReborn v1.7.0 generated an exception
java.lang.NoSuchMethodError: ru.tehkode.permissions.PermissionManager.getUser(Ljava/util/UUID;)Lru/tehkode/permissions/PermissionUser;
        at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getUser(Permission_PermissionsEx.java:243) ~[?:?]
        at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getPlayerGroups(Permission_PermissionsEx.java:252) ~[?:?]
        at com.ktar5.infoboard.API.Vault.getRank(Vault.java:24) ~[?:?]
        at com.ktar5.infoboard.Scoreboard.Create.createScoreBoard(Create.java:43) ~[?:?]
        at com.ktar5.infoboard.Scoreboard.Update.updateScoreBoard(Update.java:56) ~[?:?]
        at com.ktar5.infoboard.Timers$2.run(Timers.java:111) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]

**Comment by pixar02** [comment]
Do you even have PEX installed? And what version of Vault are you using?
